import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        <main id="main-content" role="main" className="layout-content portlet-layout">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
